title: <p align="center"> Lavanya Pasunoori </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/lavanya-p-3a44b91a9/">LinkedIn</a> |
  <a href="https://github.com/lavanyap30">GitHub</a>
  
  <br>   
  I'm a Technical Trainer. My subject expertise include C, Python, DSA, MySQL, Data Analysis through Python. Being a pythoner, I always wanted to be a Machine Learning Engineer as you know there is nothing which excites alot than training machines.
  <br>
  </p>



theme: jekyll-theme-minimal
